import { GoogleGenAI, Type } from '@google/genai';
import { AIInsightsResponse, VerifiedAnalyticsPayload } from './types';

const CONTROLLED_SYSTEM_PROMPT = `You are a business intelligence analyst.

You will receive verified analytical metrics generated by a data analytics system.

Your task is to interpret the provided metrics and generate useful business insights.

Rules:

1. Never invent numbers.
2. Never modify supplied metrics.
3. Clearly distinguish facts from recommendations.
4. Base every numerical statement only on the supplied data.
5. If information is insufficient, say so.
6. Provide practical business recommendations.
7. Keep recommendations concise and understandable.
8. Do not claim certainty about future outcomes.`;

function buildDeterministicFallback(
  payload: VerifiedAnalyticsPayload,
  notice?: string
): AIInsightsResponse {
  const growthDirection = payload.sales_growth_pct >= 0 ? 'increased' : 'decreased';
  const forecastDirection = payload.forecast_growth_pct >= 0 ? 'increase' : 'moderation';

  return {
    generatedAt: new Date().toISOString(),
    source: 'rule-based-fallback',
    modelUsed: 'Verified Deterministic BI Rules Engine',
    serviceNotice:
      notice ||
      'AI service is temporarily unavailable. Analytics and Machine Learning results are still available.',
    verifiedPayload: payload,
    executiveSummary: `Across ${payload.total_records.toLocaleString()} validated transactions (${payload.date_range.start} to ${payload.date_range.end}), total revenue reached $${payload.total_sales.toLocaleString()} across ${payload.total_orders.toLocaleString()} orders (Average Order Value: $${payload.average_order_value.toLocaleString()}), generating $${payload.total_profit.toLocaleString()} in net profit (${payload.profit_margin_pct}% profit margin). Recent period sales ${growthDirection} by ${Math.abs(payload.sales_growth_pct)}%. ${payload.top_category.name} leads category performance with $${payload.top_category.sales.toLocaleString()} (${payload.top_category.share_pct}% of total revenue), while the ${payload.weak_region.name} region shows the lowest regional revenue ($${payload.weak_region.sales.toLocaleString()}, ${payload.weak_region.margin_pct}% profit margin, ${payload.weak_region.growth_pct}% period growth).`,
    keyFindings: [
      `Total verified revenue is $${payload.total_sales.toLocaleString()} with $${payload.total_profit.toLocaleString()} net profit, yielding an overall profit margin of ${payload.profit_margin_pct}%.`,
      `Recent period sales ${growthDirection} by ${Math.abs(payload.sales_growth_pct)}% across ${payload.total_orders.toLocaleString()} orders with an Average Order Value of $${payload.average_order_value.toLocaleString()}.`,
      `${payload.top_category.name} is the top-performing category ($${payload.top_category.sales.toLocaleString()}, ${payload.top_category.share_pct}% revenue share), and "${payload.top_product.name}" is the top product ($${payload.top_product.sales.toLocaleString()} sales, $${payload.top_product.profit.toLocaleString()} profit).`,
      `The ${payload.top_region.name} region leads regional revenue at $${payload.top_region.sales.toLocaleString()} (${payload.top_region.margin_pct}% margin), whereas the ${payload.weak_region.name} region trails at $${payload.weak_region.sales.toLocaleString()} (${payload.weak_region.margin_pct}% margin, ${payload.weak_region.growth_pct}% growth).`,
      `RFM K-Means clustering identified ${payload.top_customer_segment.count} accounts in the "${payload.top_customer_segment.name}" segment generating $${payload.top_customer_segment.revenue.toLocaleString()}, alongside ${payload.at_risk_customers_count} "At Risk" customers requiring retention outreach.`,
    ],
    businessRisks: [
      `Regional underperformance in the ${payload.weak_region.name} region ($${payload.weak_region.sales.toLocaleString()} sales, ${payload.weak_region.margin_pct}% margin, ${payload.weak_region.growth_pct}% growth) drags down blended profitability.`,
      `Discount-driven margin erosion resulted in ${payload.negative_margin_orders_count} negative-margin transactions and ${payload.anomalies_detected} flagged Isolation Forest anomalies (${payload.anomaly_rate_pct}% of transactions).`,
      `Customer churn exposure across ${payload.at_risk_customers_count} "At Risk" accounts identified by RFM recency analysis.`,
    ],
    businessOpportunities: [
      `Expand inventory depth and cross-selling around ${payload.top_category.name} ($${payload.top_category.sales.toLocaleString()}, ${payload.top_category.share_pct}% share) and flagship SKU "${payload.top_product.name}".`,
      `Protect and upsell the ${payload.top_customer_segment.count} "${payload.top_customer_segment.name}" accounts that currently contribute $${payload.top_customer_segment.revenue.toLocaleString()} in revenue.`,
      `Replicate pricing and promotional discipline from the ${payload.top_region.name} region (${payload.top_region.margin_pct}% margin) into underperforming territories.`,
    ],
    recommendations: [
      {
        title: `Restructure Promotional Discounting in ${payload.weak_region.name} Region`,
        category: 'Regional & Pricing Strategy',
        impact: `Target margin recovery from ${payload.weak_region.margin_pct}% toward the company average of ${payload.profit_margin_pct}%`,
        action: `Audit sales rep discount approvals in the ${payload.weak_region.name} region and enforce a strict discount ceiling to eliminate the ${payload.negative_margin_orders_count} loss-making transactions.`,
        metricReference: `${payload.weak_region.name} Sales: $${payload.weak_region.sales.toLocaleString()} · Margin: ${payload.weak_region.margin_pct}%`,
      },
      {
        title: `Prioritize Inventory & Bundling for ${payload.top_category.name}`,
        category: 'Inventory & Merchandising',
        impact: `Sustains ${payload.top_category.share_pct}% core revenue stream ($${payload.top_category.sales.toLocaleString()})`,
        action: `Maintain buffer stock for "${payload.top_product.name}" ($${payload.top_product.sales.toLocaleString()} sales) and bundle high-margin accessories with core ${payload.top_category.name} orders.`,
        metricReference: `Top Category: ${payload.top_category.name} ($${payload.top_category.sales.toLocaleString()})`,
      },
      {
        title: `Launch Win-Back Campaign for At-Risk Customer Segment`,
        category: 'Customer Retention (RFM)',
        impact: `Mitigates churn across ${payload.at_risk_customers_count} dormant accounts`,
        action: `Deploy automated account health check-ins and volume-tied renewal incentives for the ${payload.at_risk_customers_count} At-Risk customers while assigning dedicated managers to the ${payload.top_customer_segment.count} High-Value accounts.`,
        metricReference: `At-Risk Accounts: ${payload.at_risk_customers_count} · High-Value Revenue: $${payload.top_customer_segment.revenue.toLocaleString()}`,
      },
      {
        title: `Audit Flagged Isolation Forest Transaction Anomalies`,
        category: 'Risk & Compliance',
        impact: `Addresses ${payload.anomalies_detected} anomalous orders (${payload.anomaly_rate_pct}% anomaly rate)`,
        action: `Review the ${payload.anomalies_detected} transactions isolated by the Isolation Forest model for unauthorized bulk discounting and abnormal cost spikes.`,
        metricReference: `Anomalies: ${payload.anomalies_detected} (${payload.anomaly_rate_pct}%)`,
      },
    ],
    forecastInterpretation: `The selected ${payload.forecast_model} model (R² = ${payload.forecast_r2}, MAPE = ${payload.forecast_mape_pct}%) projects next-month sales of $${payload.forecast_next_month.toLocaleString()}, representing a ${payload.forecast_growth_pct}% ${forecastDirection} relative to the most recent month. Note that statistical forecasts reflect historical trend and seasonality patterns and do not guarantee future outcomes.`,
    nextActions: [
      `Investigate the ${payload.weak_region.name} region's ${payload.weak_region.growth_pct}% growth rate and ${payload.weak_region.margin_pct}% profit margin with regional sales leadership.`,
      `Cap discretionary discounts above 25% to eliminate the ${payload.negative_margin_orders_count} negative-margin orders.`,
      `Initiate retention outreach to the ${payload.at_risk_customers_count} At-Risk customers identified by K-Means RFM segmentation.`,
      `Align procurement for next month's projected $${payload.forecast_next_month.toLocaleString()} demand horizon.`,
    ],
  };
}

export async function generateGeminiBusinessInsights(
  verifiedPayload: VerifiedAnalyticsPayload
): Promise<AIInsightsResponse> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || apiKey === 'MY_GEMINI_API_KEY' || apiKey.trim() === '') {
    return buildDeterministicFallback(
      verifiedPayload,
      'AI service is temporarily unavailable (GEMINI_API_KEY not configured). Analytics and Machine Learning results are still available via the verified BI rules engine.'
    );
  }

  try {
    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });

    const userPrompt = `Analyze the following verified analytical metrics JSON generated by our PostgreSQL + Python/TypeScript + Machine Learning pipeline and produce a comprehensive business intelligence report. Use ONLY the numbers provided in this JSON payload:

${JSON.stringify(verifiedPayload, null, 2)}`;

    const response = await ai.models.generateContent({
      model: 'gemini-3.8-flash',
      contents: userPrompt,
      config: {
        systemInstruction: CONTROLLED_SYSTEM_PROMPT,
        temperature: 0.2,
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            executiveSummary: {
              type: Type.STRING,
              description: 'Concise executive summary citing only verified numbers from the payload.',
            },
            keyFindings: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: '4 to 6 key factual observations grounded strictly in the provided metrics.',
            },
            businessRisks: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: '3 to 4 potential business risks supported by the metrics.',
            },
            businessOpportunities: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: '3 to 4 growth opportunities supported by the metrics.',
            },
            recommendations: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  title: { type: Type.STRING },
                  category: { type: Type.STRING },
                  impact: { type: Type.STRING },
                  action: { type: Type.STRING },
                  metricReference: { type: Type.STRING },
                },
                required: ['title', 'category', 'impact', 'action', 'metricReference'],
              },
              description: '4 specific, actionable management recommendations.',
            },
            forecastInterpretation: {
              type: Type.STRING,
              description: 'Explanation of what the ML forecasting model predicts and its evaluation metrics without claiming certainty.',
            },
            nextActions: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: '4 immediate next steps for executive leadership.',
            },
          },
          required: [
            'executiveSummary',
            'keyFindings',
            'businessRisks',
            'businessOpportunities',
            'recommendations',
            'forecastInterpretation',
            'nextActions',
          ],
        },
      },
    });

    const rawText = response.text;
    if (!rawText) {
      return buildDeterministicFallback(verifiedPayload);
    }

    const parsed = JSON.parse(rawText.trim());

    return {
      generatedAt: new Date().toISOString(),
      source: 'gemini-api',
      modelUsed: 'gemini-3.8-flash',
      verifiedPayload,
      executiveSummary: parsed.executiveSummary,
      keyFindings: parsed.keyFindings,
      businessRisks: parsed.businessRisks,
      businessOpportunities: parsed.businessOpportunities,
      recommendations: parsed.recommendations,
      forecastInterpretation: parsed.forecastInterpretation,
      nextActions: parsed.nextActions,
    };
  } catch (error) {
    console.warn('Gemini API fallback triggered:', error instanceof Error ? error.message : error);
    return buildDeterministicFallback(
      verifiedPayload,
      'AI service is temporarily unavailable. Analytics and Machine Learning results are still available.'
    );
  }
}
